# Generated by Django 5.0.7 on 2024-07-26 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_registrationkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='RegistrationKey',
        ),
    ]
