# Generated by Django 5.0.7 on 2024-07-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_category_options_budget_recurringtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='interval',
            field=models.CharField(help_text='e.g., daily, weekly, monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='next_occurrence',
            field=models.DateField(),
        ),
    ]
