# Generated by Django 5.0.7 on 2024-07-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_recurringtransaction_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='interval',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], help_text='e.g., daily, weekly, monthly', max_length=10),
        ),
    ]
