# Generated by Django 5.0.7 on 2024-07-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='transfer_date',
            new_name='date',
        ),
    ]
