# Generated by Django 5.0.7 on 2024-07-19 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_remove_budget_month_rule_budget_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='living',
            new_name='needs',
        ),
        migrations.AlterField(
            model_name='budget',
            name='rule',
            field=models.ForeignKey(blank=True, help_text='<span class="text-primary" style="cursor: pointer;" onclick="openAddRuleWindow()">add rule</span>', null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.rule'),
        ),
    ]
