# Generated by Django 5.0.7 on 2024-07-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_rule_needs_alter_rule_savings_alter_rule_wants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-pk']},
        ),
    ]
