# Generated by Django 5.0.7 on 2024-07-21 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_budget_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='rule',
            field=models.ForeignKey(help_text='<span class="text-primary" style="cursor: pointer;" onclick="openAddRuleWindow()">add rule</span>', null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.rule'),
        ),
    ]
